DROP TABLE IF EXISTS QUIZ_RESPONSE;
DROP SEQUENCE IF EXISTS QUIZ_RESPONSE_ID_SEQ;

CREATE SEQUENCE QUIZ_RESPONSE_ID_SEQ;
CREATE TABLE QUIZ_RESPONSE (
        QUIZ_RESPONSE_ID INTEGER DEFAULT NEXTVAL('QUIZ_RESPONSE_ID_SEQ') NOT NULL,
        ANUMBER VARCHAR(255),
        ANSWERS JSONB,
        SET_NAME varchar(255),
        RESPONSE_TIME timestamp,
        SCORE INTEGER,
        IS_ARCHIVED Boolean,
        EMAIL_SENT Boolean,
PRIMARY KEY (QUIZ_RESPONSE_ID)
      	
    );

    
DROP TABLE IF EXISTS SYS_PARAM;
DROP SEQUENCE IF EXISTS SYS_PARAM_ID_SEQ;

CREATE SEQUENCE SYS_PARAM_ID_SEQ;
CREATE TABLE SYS_PARAM (
        SYS_PARAM_ID INTEGER DEFAULT NEXTVAL('SYS_PARAM_ID_SEQ') NOT NULL,
        PARAM_NAME varchar(255),
        PARAM_VALUE varchar(255),
        PRIMARY KEY (SYS_PARAM_ID)
    );
    

DROP TABLE IF EXISTS SET_ANSWERS;
DROP SEQUENCE IF EXISTS SET_ANSWERS_ID_SEQ;

CREATE SEQUENCE SET_ANSWERS_ID_SEQ;
CREATE TABLE SET_ANSWERS (
        SET_ANSWERS_ID INTEGER DEFAULT NEXTVAL('SET_ANSWERS_ID_SEQ') NOT NULL,
        SET_NAME varchar(255),
        ANSWERS JSON,
        PRIMARY KEY (SET_ANSWERS_ID)
    );