INSERT INTO SYS_PARAM(PARAM_NAME, PARAM_VALUE) VALUES('ACTIVE_SET', 'SET 1');
INSERT INTO SYS_PARAM(PARAM_NAME, PARAM_VALUE) VALUES('SEND_EMAIL', 'TRUE');

UPDATE SYS_PARAM SET PARAM_VALUE = 'SET 2' WHERE PARAM_NAME= 'ACTIVE_SET';
UPDATE SYS_PARAM SET PARAM_VALUE = 'TRUE' WHERE PARAM_NAME= 'SEND_EMAIL';

INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 1', '{"answers": ["A", "C", "B"]}');
INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 2', '{"answers": ["C", "B", "C"]}');
INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 3', '{"answers": ["A", "B", "A"]}');

DELETE FROM SET_ANSWERS;

INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 1', '{"answers": ["C", "B", "B"]}');
INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 2', '{"answers": ["D", "C", "C"]}');
INSERT INTO SET_ANSWERS(SET_NAME, ANSWERS) VALUES('SET 3', '{"answers": ["C", "A", "B"]}');